server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:inventario-db
    driverClassName: org.h2.Driver
    username: sa
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mensaje: "Bienvenido al servicio de Inventario"

