server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:inventario-db
    driverClassName: org.h2.Driver
    username: sa
    password: password

mensaje: "Bienvenido al servicio de Inventario"

